# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
general:
  branches:
    only:
      - src
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "spec/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: (cd spec && npm install --frozen-lockfile)

      - run:
          name: Test Packages
          command: chmod +x ./.circleci/entry_point.sh && ./.circleci/entry_point.sh

      - save_cache:
          paths:
            - spec/node_modules
          key: v1-dependencies-{{ checksum "spec/package.json" }}